services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_api_development
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate:status | grep -q 'down' && bundle exec rails db:migrate || echo 'No pending migrations' && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:password@db/blog_api_development
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/app"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis