services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_api_test
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  setup_test_db:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate RAILS_ENV=test"
    volumes:
      - ".:/app"
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db/blog_api_test
    depends_on:
      - db

  test:
    build: .
    command: bash -c "bundle exec rspec --format documentation"
    volumes:
      - ".:/app"
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db/blog_api_test
    depends_on:
      - setup_test_db
      - redis